---
abstract: 'Process a directory of Mason templates'
author:
  - 'Jonathan Swartz <swartz@pobox.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200008, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MasonX-ProcessDir
requires:
  Any::Template::ProcessDir: 0.04
  Mason: 2.10
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=MasonX-ProcessDir
  repository: git://github.com/jonswar/perl-masonx-processdir.git
version: 0.01
